apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-management-backend
  labels:
    app: member-management
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: member-management
      tier: backend
  template:
    metadata:
      labels:
        app: member-management
        tier: backend
    spec:
      containers:
      - name: backend
        image: member-management-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: member-management-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: member-management-secrets
              key: secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: member-management-backend-service
  labels:
    app: member-management
    tier: backend
spec:
  selector:
    app: member-management
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-management-frontend
  labels:
    app: member-management
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: member-management
      tier: frontend
  template:
    metadata:
      labels:
        app: member-management
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: member-management-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: member-management-frontend-service
  labels:
    app: member-management
    tier: frontend
spec:
  selector:
    app: member-management
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: member-management-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: member-management.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: member-management-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: member-management-frontend-service
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: member-management-secrets
type: Opaque
data:
  database-url: <base64-encoded-database-url>
  secret-key: <base64-encoded-secret-key>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: member-management-config
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "member_management"
  DATABASE_USER: "postgres"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
