"""Add member_metadata and member_dynamic_data tables with indexes

Revision ID: xxxx
Revises: 
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'xxxx'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create member_metadata table
    op.create_table('member_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create member_dynamic_data table
    op.create_table('member_dynamic_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('member_id', sa.Integer(), nullable=False),
        sa.Column('data_type', sa.String(length=50), nullable=False),
        sa.Column('data_value', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for performance optimization
    op.create_index('ix_member_metadata_member_id', 'member_metadata', ['member_id'], unique=False)
    op.create_index('ix_member_metadata_key', 'member_metadata', ['key'], unique=False)
    op.create_index('ix_member_dynamic_data_member_id', 'member_dynamic_data', ['member_id'], unique=False)
    op.create_index('ix_member_dynamic_data_data_type', 'member_dynamic_data', ['data_type'], unique=False)
    op.create_index('ix_member_dynamic_data_timestamp', 'member_dynamic_data', ['timestamp'], unique=False)
    
    # Add composite indexes for common queries
    op.create_index('ix_member_metadata_member_key', 'member_metadata', ['member_id', 'key'], unique=False)
    op.create_index('ix_member_dynamic_data_member_type', 'member_dynamic_data', ['member_id', 'data_type'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_member_dynamic_data_member_type', table_name='member_dynamic_data')
    op.drop_index('ix_member_metadata_member_key', table_name='member_metadata')
    op.drop_index('ix_member_dynamic_data_timestamp', table_name='member_dynamic_data')
    op.drop_index('ix_member_dynamic_data_data_type', table_name='member_dynamic_data')
    op.drop_index('ix_member_dynamic_data_member_id', table_name='member_dynamic_data')
    op.drop_index('ix_member_metadata_key', table_name='member_metadata')
    op.drop_index('ix_member_metadata_member_id', table_name='member_metadata')
    
    # Drop tables
    op.drop_table('member_dynamic_data')
    op.drop_table('member_metadata')
    
    # ### end Alembic commands ###
