# Generated by Django 5.2.8 on 2025-12-30 13:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_project_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('agentscope_project_id', models.CharField(db_index=True, max_length=100, verbose_name='agentscope project ID')),
                ('agentscope_agent_id', models.CharField(max_length=100, verbose_name='agentscope agent ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('round_index', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('llm_calls', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_records', to='api.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Execution Record',
                'verbose_name_plural': 'Execution Records',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='observabili_tenant__a3689a_idx'), models.Index(fields=['tenant', 'agentscope_project_id'], name='observabili_tenant__94c3f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(max_length=50)),
                ('agentscope_project_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('agentscope_agent_id', models.CharField(blank=True, max_length=100)),
                ('node_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='observabili_tenant__112752_idx'), models.Index(fields=['agentscope_project_id', 'timestamp'], name='observabili_agentsc_7db006_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('agentscope_project_id', models.CharField(db_index=True, max_length=100, verbose_name='agentscope project ID')),
                ('agentscope_agent_id', models.CharField(max_length=100, verbose_name='agentscope agent ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Cost (USD)')),
                ('duration_ms', models.FloatField(default=0, verbose_name='Duration (ms)')),
                ('span_id', models.CharField(blank=True, max_length=100)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='api.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Usage Record',
                'verbose_name_plural': 'Usage Records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='observabili_tenant__c6031a_idx'), models.Index(fields=['tenant', 'agentscope_project_id'], name='observabili_tenant__ec0cbe_idx'), models.Index(fields=['agentscope_project_id', 'timestamp'], name='observabili_agentsc_7648cb_idx')],
            },
        ),
    ]
