"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (use absolute path)
env_path = BASE_DIR / '.env'
load_dotenv(env_path)


def _parse_database_url(url: str) -> dict:
    """Parse DATABASE_URL into Django database config.

    Args:
        url (`str`):
            Database URL in format: postgres://user:pass@host:port/dbname

    Returns:
        `dict`:
            Django DATABASES config
    """
    import re
    match = re.match(
        r'postgres(?:ql)?://(?P<user>[^:]+):(?P<password>[^@]+)@(?P<host>[^:]+):(?P<port>\d+)/(?P<name>.+)',
        url
    )
    if match:
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': match.group('name'),
            'USER': match.group('user'),
            'PASSWORD': match.group('password'),
            'HOST': match.group('host'),
            'PORT': match.group('port'),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    return None


def _get_aws_secret(secret_name: str, region: str = "ap-northeast-1") -> dict:
    """Retrieve secret from AWS Secrets Manager.

    Uses IAM role credentials automatically when running on EC2.
    Falls back to environment variables for local development.

    Args:
        secret_name (`str`):
            The name of the secret in Secrets Manager
        region (`str`, optional):
            AWS region. Defaults to ap-northeast-1

    Returns:
        `dict`:
            The secret as a dictionary
    """
    try:
        import boto3
        from botocore.exceptions import ClientError

        client = boto3.client("secretsmanager", region_name=region)
        response = client.get_secret_value(SecretId=secret_name)
        return json.loads(response["SecretString"])
    except Exception:
        # Fallback for local development
        return {}


# Environment detection
USE_AWS = os.environ.get("USE_AWS", "false").lower() == "true"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-90uxb-s=cl467h%m8!g#e7&4&!k#&6$&uqszneyt=dhu)+gpvz')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'storages',  # django-storages for S3
    'django_filters',
    # Local apps
    'api',
    'tenants',
    'observability',
    'execution',
    'authentication',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenants.middleware.TenantMiddleware',  # Multi-tenancy
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration priority:
# 1. DATABASE_URL environment variable
# 2. USE_AWS=true with AWS Secrets Manager
# 3. Default SQLite for local development

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Use DATABASE_URL (e.g., postgres://user:pass@host:port/dbname)
    _db_config = _parse_database_url(DATABASE_URL)
    if _db_config:
        DATABASES = {'default': _db_config}
    else:
        raise ValueError(f"Invalid DATABASE_URL format: {DATABASE_URL}")
elif USE_AWS:
    # Production: Use AWS RDS PostgreSQL with credentials from Secrets Manager
    _db_secret = _get_aws_secret("hivecore/db-credentials")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _db_secret.get('dbname', 'hivecore'),
            'USER': _db_secret.get('username', 'hivecore'),
            'PASSWORD': _db_secret.get('password', ''),
            'HOST': _db_secret.get('host', ''),
            'PORT': _db_secret.get('port', 5432),
            'OPTIONS': {
                'connect_timeout': 10,
            },
        }
    }
else:
    # Development: Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

if USE_AWS:
    # Production: Use S3 for media files with CloudFront CDN
    # AWS credentials are obtained automatically from IAM role (no keys in code)
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION', 'ap-northeast-1')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_S3_BUCKET', 'hivecore-media-1766251565')

    # CloudFront CDN domain for faster global delivery
    AWS_CLOUDFRONT_DOMAIN = os.environ.get('AWS_CLOUDFRONT_DOMAIN', 'd26rgfbarpilag.cloudfront.net')
    AWS_S3_CUSTOM_DOMAIN = AWS_CLOUDFRONT_DOMAIN  # Use CloudFront instead of direct S3

    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_QUERYSTRING_AUTH = False  # Public URLs for avatars

    # Media files (avatars, uploads) use S3 via CloudFront
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

    # Static files still served locally or via collectstatic
    STATIC_URL = 'static/'
    STATICFILES_DIRS = [
        BASE_DIR / 'api' / 'static',
    ]

    # CloudFront URL for avatars (used by load_data.py)
    AVATAR_BASE_URL = f'https://{AWS_CLOUDFRONT_DOMAIN}/avatars'
else:
    # Development: Use local storage
    STATIC_URL = 'static/'
    STATICFILES_DIRS = [
        BASE_DIR / 'api' / 'static',
    ]
    STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic in production
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    AVATAR_BASE_URL = os.environ.get('AVATAR_BASE_URL', 'http://localhost:8000/static/avatars')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _cors_origins:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(',') if origin.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOW_ALL_ORIGINS = True  # For development only

CORS_ALLOW_CREDENTIALS = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'authentication.backends.JWTAuthenticationWithTenant',
        'authentication.backends.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # For admin/dev
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Simple JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# Redis URL (for SSE pub/sub and caching)
REDIS_URL = os.environ.get('REDIS_URL', None)  # e.g., redis://localhost:6379/0

# Cache configuration
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    # Fallback to database cache for local development without Redis
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': 'django_cache_table',
        }
    }

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL or 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = REDIS_URL or 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 3600  # 1 hour max per task

# Execution settings
EXECUTION_WORKSPACE_DIR = os.environ.get('EXECUTION_WORKSPACE_DIR', '/tmp/hivecore_workspaces')
INTERNAL_API_URL = os.environ.get('INTERNAL_API_URL', 'http://localhost:8000')

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'HiveCore API',
    'DESCRIPTION': 'API for HiveCore multi-agent orchestration system',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# OAuth Configuration
# GitHub OAuth
GITHUB_CLIENT_ID = os.environ.get('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.environ.get('GITHUB_CLIENT_SECRET', '')
GITHUB_REDIRECT_URI = os.environ.get(
    'GITHUB_REDIRECT_URI',
    'http://localhost:5173/oauth/callback/github'
)

# WeChat OAuth (微信开放平台)
WECHAT_APP_ID = os.environ.get('WECHAT_APP_ID', '')
WECHAT_APP_SECRET = os.environ.get('WECHAT_APP_SECRET', '')
WECHAT_REDIRECT_URI = os.environ.get(
    'WECHAT_REDIRECT_URI',
    'http://localhost:5173/oauth/callback/wechat'
)

# QQ OAuth (QQ互联)
QQ_APP_ID = os.environ.get('QQ_APP_ID', '')
QQ_APP_SECRET = os.environ.get('QQ_APP_SECRET', '')
QQ_REDIRECT_URI = os.environ.get(
    'QQ_REDIRECT_URI',
    'http://localhost:5173/oauth/callback/qq'
)

# Firebase (预留，暂不实现)
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', '')
FIREBASE_PRIVATE_KEY = os.environ.get('FIREBASE_PRIVATE_KEY', '')
