# -*- coding: utf-8 -*-
"""AssistantAgent scoring and selection helpers."""
from ._types import (
    AAScoringConfig,
    AgentCapabilities,
    AgentProfile,
    CandidateRanking,
    RequirementFitBreakdown,
    RequirementHardConstraints,
    Requirement,
    RoleRequirement,  # Alias for backward compatibility
    SelectionDecision,
    SelectionAuditLog,
    SelectionRound,
    StaticScore,
    FaultLedger,
    FaultRecord,
)
from ._selector import AssistantAgentSelector, RequirementFitScorer
from ._team_selector import (
    TeamSelector,
    TeamSelection,
    TeamTemplate,
    TeamRole,
    RoleAssignment,
    CollaborationMode,
    LLMTeamAnalysis,
    AgentSpec,
    TEAM_TEMPLATES,
    ROLE_CAPABILITIES,
    suggest_agents_for_requirements,
)
from ._agent_registry import (
    AgentRegistry,
    AgentRegistryEntry,
    DomainInfo,
    TagInfo,
    CORE_DOMAINS,
    create_agent_registry_entry,
    get_global_registry,
    load_agent_profile_from_manifest,
    load_all_agent_profiles,
)
from ._registry_tools import (
    RegistryIndex,
    get_registry_index,
    create_registry_tools,
    execute_registry_tool,
)
from ._vocabulary import (
    CORE_DOMAINS as VOCABULARY_CORE_DOMAINS,
    DOMAIN_HIERARCHY,
    DOMAIN_SYNONYMS,
    CANONICAL_SKILLS,
    normalize_skill,
    normalize_skills,
    normalize_domain,
    normalize_domains,
    get_primary_domain,
    is_core_domain,
    expand_skill_synonyms,
    skill_match_score,
    domain_match_score,
)

__all__ = [
    "AAScoringConfig",
    "AgentCapabilities",
    "AgentProfile",
    "CandidateRanking",
    "RequirementFitBreakdown",
    "RequirementHardConstraints",
    "Requirement",
    "RoleRequirement",  # Alias for backward compatibility
    "SelectionDecision",
    "SelectionAuditLog",
    "SelectionRound",
    "StaticScore",
    "FaultLedger",
    "FaultRecord",
    "AssistantAgentSelector",
    "RequirementFitScorer",
    # Team selection (multi-agent)
    "TeamSelector",
    "TeamSelection",
    "TeamTemplate",
    "TeamRole",
    "RoleAssignment",
    "CollaborationMode",
    "LLMTeamAnalysis",
    "AgentSpec",
    "TEAM_TEMPLATES",
    "ROLE_CAPABILITIES",
    "suggest_agents_for_requirements",
    # Agent registry (for Django migration)
    "AgentRegistry",
    "AgentRegistryEntry",
    "DomainInfo",
    "TagInfo",
    "CORE_DOMAINS",
    "create_agent_registry_entry",
    "get_global_registry",
    "load_agent_profile_from_manifest",
    "load_all_agent_profiles",
    # Registry query tools
    "RegistryIndex",
    "get_registry_index",
    "create_registry_tools",
    "execute_registry_tool",
    # Vocabulary normalization
    "VOCABULARY_CORE_DOMAINS",
    "DOMAIN_HIERARCHY",
    "DOMAIN_SYNONYMS",
    "CANONICAL_SKILLS",
    "normalize_skill",
    "normalize_skills",
    "normalize_domain",
    "normalize_domains",
    "get_primary_domain",
    "is_core_domain",
    "expand_skill_synonyms",
    "skill_match_score",
    "domain_match_score",
]
