# Generated by Django 5.2.8 on 2025-12-30 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Tenant name')),
                ('slug', models.SlugField(unique=True, verbose_name='Unique slug')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('team', 'Team'), ('business', 'Business')], default='free', max_length=20, verbose_name='Subscription tier')),
                ('api_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='API Key')),
                ('max_tokens_per_month', models.BigIntegerField(default=500000, verbose_name='Max tokens per month')),
                ('max_projects', models.IntegerField(default=10, verbose_name='Max projects')),
                ('max_agents_per_project', models.IntegerField(default=10, verbose_name='Max agents per project')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenant Users',
            },
        ),
    ]
