# Generated by Django 5.2.8 on 2025-12-09 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='agent_type',
            field=models.CharField(blank=True, choices=[('FE', 'Frontend'), ('BE', 'Backend'), ('PM', 'Project Manager'), ('QA', 'Quality Assurance'), ('Design', 'Design')], max_length=20, verbose_name='Agent type'),
        ),
        migrations.CreateModel(
            name='AgentCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent')], default='received', max_length=20)),
                ('content', models.TextField(verbose_name='Message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='api.agent')),
                ('from_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_collaborations', to='api.agent', verbose_name='From agent (for received)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_collaborations', to='api.project')),
                ('to_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_collaborations', to='api.agent', verbose_name='To agent (for sent)')),
            ],
            options={
                'verbose_name': 'Agent Collaboration',
                'verbose_name_plural': 'Agent Collaborations',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Task category (e.g., A. 项目启动)')),
                ('content', models.TextField(verbose_name='Task item content')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Is checked')),
                ('order', models.IntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='api.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_task_items', to='api.project')),
            ],
            options={
                'verbose_name': 'Agent Task Item',
                'verbose_name_plural': 'Agent Task Items',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AgentThinking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Thinking content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thinkings', to='api.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_thinkings', to='api.project')),
            ],
            options={
                'verbose_name': 'Agent Thinking',
                'verbose_name_plural': 'Agent Thinkings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Folder name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.folder', verbose_name='Parent folder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.project')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='File name')),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('video', 'Video'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('code', 'Code'), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.BigIntegerField(default=0, verbose_name='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('url', models.URLField(blank=True, verbose_name='File URL or path')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('description', models.TextField(blank=True, verbose_name='File description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.folder', verbose_name='Parent folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['name'],
            },
        ),
    ]
