# Generated by Django 5.2.8 on 2025-12-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_agent_type_agentcollaboration_agenttaskitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cost ($)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='Current progress'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='progress_total',
            field=models.IntegerField(default=100, verbose_name='Total progress'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Error', 'Error'), ('Working', 'Working'), ('Await', 'Await')], default='Await', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='time_spent',
            field=models.CharField(blank=True, max_length=50, verbose_name='Time spent'),
        ),
    ]
