# Generated by Django 5.2.8 on 2025-12-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teammember_cost_teammember_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='first_user_message',
            field=models.TextField(blank=True, verbose_name='First user message (for quick display)'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='source_type',
            field=models.CharField(blank=True, choices=[('upload_doc', '上传文档'), ('memory', '读取记忆'), ('community', '社区论坛'), ('no_data', '无数据来源')], max_length=20, verbose_name='Data source type'),
        ),
    ]
