# Generated by Django 5.2.8 on 2025-12-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_conversation_source_type'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='tenants.tenant', verbose_name='Tenant'),
        ),
    ]
