# Generated by Django 5.2.8 on 2025-12-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_tenant'),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('tech_stack', 'Tech Stack'), ('architecture', 'Architecture'), ('file_structure', 'File Structure'), ('api_design', 'API Design'), ('component', 'Component'), ('constraint', 'Constraint'), ('dependency', 'Dependency'), ('tooling', 'Tooling')], max_length=50, verbose_name='Decision category')),
                ('key', models.CharField(max_length=200, verbose_name='Decision key (e.g., frontend_framework, linter)')),
                ('value', models.TextField(verbose_name='Decision value (e.g., Vue 3, ESLint)')),
                ('description', models.TextField(blank=True, verbose_name='Human-readable explanation/rationale')),
                ('made_by_agent_name', models.CharField(blank=True, max_length=100, verbose_name='Agent name (preserved even if agent deleted)')),
                ('round_index', models.IntegerField(default=0, verbose_name='Round index when decision was made')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is this decision still active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='execution.executionround', verbose_name='Execution round')),
                ('made_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to='api.agent', verbose_name='Agent that made this decision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='api.project', verbose_name='Project')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='api.projectdecision', verbose_name='Newer decision that replaced this one')),
            ],
            options={
                'verbose_name': 'Project Decision',
                'verbose_name_plural': 'Project Decisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'category'], name='api_project_project_7193a8_idx'), models.Index(fields=['project', 'category', 'key'], name='api_project_project_a1f4ae_idx'), models.Index(fields=['execution_round'], name='api_project_executi_d9e05b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'category', 'key'), name='unique_active_decision_per_project')],
            },
        ),
        migrations.CreateModel(
            name='ProjectFileRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='Relative file path from workspace root')),
                ('description', models.TextField(verbose_name="Brief description of the file's purpose")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_files', to='api.agent', verbose_name='Agent that created this file')),
                ('execution_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_files', to='execution.executionround', verbose_name='Execution round')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_registry', to='api.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project File Registry',
                'verbose_name_plural': 'Project File Registries',
                'ordering': ['file_path'],
                'unique_together': {('project', 'file_path')},
            },
        ),
    ]
