# Generated by Django 5.2.8 on 2025-12-31 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_project_decisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='File name')),
                ('file_type', models.CharField(max_length=50, verbose_name='File type')),
                ('summary', models.TextField(blank=True, verbose_name='AI summary of file content')),
                ('text_content', models.TextField(blank=True, verbose_name='Extracted text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='api.file', verbose_name='Attached file')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.message', verbose_name='Parent message')),
            ],
            options={
                'verbose_name': 'Message Attachment',
                'verbose_name_plural': 'Message Attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
