# Generated by Django 5.2.8 on 2026-01-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_main_project', to='api.conversation', verbose_name='Main conversation for requirements'),
        ),
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('conversation', '需求对话'), ('team_building', '团队组建'), ('working', '工作中'), ('delivery', '交付')], default='conversation', max_length=20, verbose_name='Current workflow phase'),
        ),
    ]
