# Generated by Django 5.2.8 on 2025-12-31 06:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('github', 'GitHub'), ('firebase', 'Firebase')], max_length=20, verbose_name='OAuth Provider')),
                ('provider_uid', models.CharField(max_length=255, verbose_name='Provider User ID')),
                ('union_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Union ID (WeChat)')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Extra Data')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'indexes': [models.Index(fields=['provider', 'provider_uid'], name='authenticat_provide_5cb781_idx'), models.Index(fields=['user', 'provider'], name='authenticat_user_id_36c1fa_idx'), models.Index(fields=['union_id'], name='authenticat_union_i_e33244_idx')],
                'unique_together': {('provider', 'provider_uid')},
            },
        ),
    ]
