# Generated by Django 5.2.8 on 2025-12-30 14:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_project_tenant'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('requirement_text', models.TextField(blank=True, help_text='The requirement text for this execution')),
                ('options', models.JSONField(default=dict, help_text='Execution options (max_rounds, parallel, etc.)')),
                ('summary', models.TextField(blank=True, help_text='Execution summary')),
                ('error_message', models.TextField(blank=True)),
                ('total_tokens', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_llm_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_rounds', to='api.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionProgress',
            fields=[
                ('execution_round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='progress', serialize=False, to='execution.executionround')),
                ('current_phase', models.CharField(default='initializing', max_length=50)),
                ('current_agent', models.CharField(blank=True, max_length=100)),
                ('current_task', models.CharField(blank=True, max_length=255)),
                ('progress_percent', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_requirements', models.IntegerField(default=0)),
                ('total_requirements', models.IntegerField(default=0)),
                ('last_event', models.CharField(blank=True, max_length=50)),
                ('last_event_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('source', models.CharField(blank=True, help_text='Log source (e.g., module name)', max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='api.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
                ('execution_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='execution.executionround')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('code', 'Code'), ('config', 'Config'), ('document', 'Document'), ('test', 'Test'), ('style', 'Style'), ('asset', 'Asset'), ('other', 'Other')], default='code', max_length=20)),
                ('file_path', models.CharField(help_text='Relative path in workspace', max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, help_text='Programming language if code', max_length=50)),
                ('content', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, help_text='SHA256 hash of content', max_length=64)),
                ('size_bytes', models.IntegerField(default=0)),
                ('s3_key', models.CharField(blank=True, help_text='S3 key if stored externally', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_artifacts', to='api.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
                ('execution_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='execution.executionround')),
            ],
            options={
                'ordering': ['file_path'],
            },
        ),
        migrations.CreateModel(
            name='AgentSelectionDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s_base_score', models.FloatField(default=0, help_text='Base capability score')),
                ('requirement_fit_score', models.FloatField(default=0, help_text='Requirement fit score')),
                ('total_score', models.FloatField(default=0, help_text='Combined total score')),
                ('scoring_breakdown', models.JSONField(default=dict, help_text='Detailed scoring breakdown')),
                ('reasons', models.TextField(blank=True, help_text='Selection reasons')),
                ('role_assigned', models.CharField(blank=True, help_text='Role assigned to agent', max_length=100)),
                ('selection_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_decisions', to='api.agent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
                ('execution_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_selections', to='execution.executionround')),
            ],
            options={
                'ordering': ['selection_order'],
            },
        ),
        migrations.AddIndex(
            model_name='executionround',
            index=models.Index(fields=['project', 'round_number'], name='execution_e_project_8d9caa_idx'),
        ),
        migrations.AddIndex(
            model_name='executionround',
            index=models.Index(fields=['status'], name='execution_e_status_ace768_idx'),
        ),
        migrations.AddIndex(
            model_name='executionround',
            index=models.Index(fields=['celery_task_id'], name='execution_e_celery__a4f109_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['execution_round', 'level'], name='execution_e_executi_0aea47_idx'),
        ),
        migrations.AddIndex(
            model_name='executionlog',
            index=models.Index(fields=['timestamp'], name='execution_e_timesta_9ee9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='executionartifact',
            index=models.Index(fields=['execution_round', 'artifact_type'], name='execution_e_executi_b910e2_idx'),
        ),
        migrations.AddIndex(
            model_name='executionartifact',
            index=models.Index(fields=['file_path'], name='execution_e_file_pa_68a946_idx'),
        ),
        migrations.AddIndex(
            model_name='agentselectiondecision',
            index=models.Index(fields=['execution_round', 'selection_order'], name='execution_a_executi_7efaf6_idx'),
        ),
    ]
