# Generated by Django 5.2.8 on 2025-12-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_project_decisions'),
        ('execution', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentselectiondecision',
            name='agent_name',
            field=models.CharField(blank=True, help_text='Cached agent name', max_length=100),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='batch_index',
            field=models.IntegerField(default=0, help_text='Selection batch index'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='cold_start_slot_reserved',
            field=models.BooleanField(default=False, help_text='Whether cold start bonus was applied'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='decision_source',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User')], default='system', help_text='How the selection was made', max_length=10),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='is_cold_start',
            field=models.BooleanField(default=False, help_text='Whether agent was in cold start'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='Whether this agent was actually selected'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='requirement_fit_matched',
            field=models.JSONField(default=dict, help_text='Matched capabilities by field {field: [values]}'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='requirement_fit_missing',
            field=models.JSONField(default=dict, help_text='Missing capabilities by field {field: [values]}'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='requirement_fit_partial',
            field=models.JSONField(default=dict, help_text='Partial match scores by field {field: score}'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='requirement_fit_rationales',
            field=models.JSONField(default=list, help_text='Explanation rationales for requirement fit'),
        ),
        migrations.AddField(
            model_name='agentselectiondecision',
            name='risk_notes',
            field=models.JSONField(default=list, help_text='Risk notes for this candidate'),
        ),
        migrations.AlterField(
            model_name='agentselectiondecision',
            name='reasons',
            field=models.TextField(blank=True, help_text='Selection reasons (legacy)'),
        ),
        migrations.AlterField(
            model_name='agentselectiondecision',
            name='selection_order',
            field=models.IntegerField(default=0, help_text='Rank order (0 = best)'),
        ),
        migrations.AddIndex(
            model_name='agentselectiondecision',
            index=models.Index(fields=['execution_round', 'is_selected'], name='execution_a_executi_cfad24_idx'),
        ),
        migrations.AddIndex(
            model_name='agentselectiondecision',
            index=models.Index(fields=['agent', 'created_at'], name='execution_a_agent_i_5e209b_idx'),
        ),
    ]
