# Generated by Django 5.2.9 on 2026-01-05 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_add_selection_decision_details'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionprogress',
            name='current_inner_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='executionprogress',
            name='current_requirement_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='executionround',
            name='acceptance_map',
            field=models.JSONField(blank=True, help_text='Acceptance criteria map', null=True),
        ),
        migrations.AddField(
            model_name='executionround',
            name='current_inner_round',
            field=models.IntegerField(default=0, help_text='Current inner round number for task sharding'),
        ),
        migrations.AddField(
            model_name='executionround',
            name='failed_requirements',
            field=models.IntegerField(default=0, help_text='Number of failed requirements'),
        ),
        migrations.AddField(
            model_name='executionround',
            name='parsed_spec',
            field=models.JSONField(blank=True, help_text='Parsed requirement specification', null=True),
        ),
        migrations.AddField(
            model_name='executionround',
            name='passed_requirements',
            field=models.IntegerField(default=0, help_text='Number of passed requirements'),
        ),
        migrations.AddField(
            model_name='executionround',
            name='total_inner_rounds',
            field=models.IntegerField(default=0, help_text='Total completed inner rounds'),
        ),
        migrations.AddField(
            model_name='executionround',
            name='total_requirements',
            field=models.IntegerField(default=0, help_text='Total number of requirements'),
        ),
        migrations.AddField(
            model_name='executionround',
            name='use_task_sharding',
            field=models.BooleanField(default=False, help_text='Whether to use task sharding mode'),
        ),
        migrations.CreateModel(
            name='RequirementExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requirement_id', models.CharField(db_index=True, help_text='e.g., REQ-001', max_length=50)),
                ('requirement_content', models.TextField(help_text='Requirement description')),
                ('requirement_type', models.CharField(blank=True, help_text='e.g., backend, frontend, database', max_length=50)),
                ('inner_round_number', models.IntegerField(default=1, help_text='Inner round number for retries')),
                ('attempt_number', models.IntegerField(default=1, help_text='Attempt number within this round')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('depends_on', models.JSONField(default=list, help_text='List of requirement IDs this depends on')),
                ('blueprint', models.JSONField(blank=True, help_text='Blueprint design result', null=True)),
                ('code_result', models.JSONField(blank=True, help_text='Code generation result', null=True)),
                ('qa_result', models.JSONField(blank=True, help_text='QA acceptance result', null=True)),
                ('validation_result', models.JSONField(blank=True, help_text='Code validation result', null=True)),
                ('acceptance_criteria_total', models.IntegerField(default=0, help_text='Total acceptance criteria')),
                ('acceptance_criteria_passed', models.IntegerField(default=0, help_text='Passed acceptance criteria')),
                ('pass_rate', models.FloatField(default=0.0, help_text='Pass rate (0.0 - 1.0)')),
                ('is_passed', models.BooleanField(default=False, help_text='Whether requirement passed (pass_rate >= threshold)')),
                ('modified_files', models.JSONField(default=list, help_text='List of files modified by this requirement')),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('llm_calls', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_traceback', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_executions', to='execution.executionround')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'ordering': ['inner_round_number', 'requirement_id'],
            },
        ),
        migrations.AddField(
            model_name='executionartifact',
            name='requirement_execution',
            field=models.ForeignKey(blank=True, help_text='The requirement execution that generated this artifact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='execution.requirementexecution'),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='requirement_execution',
            field=models.ForeignKey(blank=True, help_text='The requirement execution this log belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='execution.requirementexecution'),
        ),
        migrations.AddIndex(
            model_name='requirementexecution',
            index=models.Index(fields=['execution_round', 'inner_round_number'], name='execution_r_executi_7c581d_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementexecution',
            index=models.Index(fields=['execution_round', 'status'], name='execution_r_executi_08733b_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementexecution',
            index=models.Index(fields=['requirement_id'], name='execution_r_require_609961_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementexecution',
            index=models.Index(fields=['celery_task_id'], name='execution_r_celery__91718a_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementexecution',
            constraint=models.UniqueConstraint(fields=('execution_round', 'requirement_id', 'inner_round_number'), name='unique_req_per_inner_round'),
        ),
    ]
